[package]
name = "ckb-hash"
version = "0.110.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "CKB default hash function."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
blake2b-rs = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
blake2b-ref = "0.2.0"
