version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: ctrlc
    versions:
    - 3.1.9
  - dependency-name: futures
    versions:
    - 0.3.12
  - dependency-name: hyper
    versions:
    - 0.13.10
  rebase-strategy: disabled
