[package]
name = "ckb-fixed-hash-core"
version = "0.110.0-pre"
license = "MIT"
authors = ["Nervos <dev@nervos.org>"]
edition = "2021"
description = "Provide several fixed-length binary data, aka fixed-sized hashes."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
thiserror = "1.0.22"
serde = { version = "1.0", features = ["derive"] }
faster-hex = "0.6"

[dev-dependencies]
serde_json = "1.0"
