[package]
name = "ckb-app-config"
version = "0.110.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
license = "MIT"
description = "CKB command line arguments and config options."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
clap = { version = "4", features = ["string"] }
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3.0"
serde_json = "1.0"
toml = "0.5"
path-clean = "0.1.0"
ckb-logger = { path = "../../util/logger", version = "= 0.110.0-pre" }
ckb-logger-config = { path = "../../util/logger-config", version = "= 0.110.0-pre" }
ckb-metrics-config = { path = "../../util/metrics-config", version = "= 0.110.0-pre" }
ckb-chain-spec = {path = "../../spec", version = "= 0.110.0-pre"}
ckb-jsonrpc-types = {path = "../jsonrpc-types", version = "= 0.110.0-pre"}
ckb-pow = { path = "../../pow", version = "= 0.110.0-pre" }
ckb-resource = { path = "../../resource", version = "= 0.110.0-pre"}
ckb-build-info = { path = "../build-info", version = "= 0.110.0-pre" }
ckb-types = { path = "../types", version = "= 0.110.0-pre" }
secio = { version="0.5.7", package="tentacle-secio" }
multiaddr = { version="0.3.0", package="tentacle-multiaddr" }
rand = "0.7"
sentry = { version = "0.26.0", optional = true }
ckb-systemtime = { path = "../systemtime", version = "= 0.110.0-pre" }
url = { version = "2.2.2", features = ["serde"] }
ubyte = { version = "0.10", features = ["serde"] }

[features]
with_sentry = ["sentry"]

[dev-dependencies]
tempfile.workspace = true
ckb-systemtime = { path = "../systemtime", version = "= 0.110.0-pre" ,features = ["enable_faketime"]}
