[package]
name = "ckb-crypto"
version = "0.110.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "The ckb crypto util"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-fixed-hash = { path = "../fixed-hash", version = "= 0.110.0-pre" }
lazy_static = "1.3"
secp256k1 = { version = "0.24", features = ["recovery"], optional = true }
thiserror = "1.0.22"
rand = { version = "0.7", features = ["small_rng"] }
faster-hex = "0.6"

[features]
default = [ "secp" ]
secp = ["secp256k1"]
